//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvalonWizard.Design.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AvalonWizard.Design.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Page.
        /// </summary>
        public static string AddPageText {
            get {
                return ResourceManager.GetString("AddPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to First Page.
        /// </summary>
        public static string FirstPageText {
            get {
                return ResourceManager.GetString("FirstPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Page.
        /// </summary>
        public static string InsertPageText {
            get {
                return ResourceManager.GetString("InsertPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Last Page.
        /// </summary>
        public static string LastPageText {
            get {
                return ResourceManager.GetString("LastPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Next Page.
        /// </summary>
        public static string NextPageText {
            get {
                return ResourceManager.GetString("NextPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string PagesMenuGroup {
            get {
                return ResourceManager.GetString("PagesMenuGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Previous Page.
        /// </summary>
        public static string PreviousPageText {
            get {
                return ResourceManager.GetString("PreviousPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Page.
        /// </summary>
        public static string RemovePageText {
            get {
                return ResourceManager.GetString("RemovePageText", resourceCulture);
            }
        }
    }
}
